### ISSUE TITLE
Problem with .tar  files while downloading

### ISSUE THREAD

**Issue by telegrambotdev** [patheticGeek/gdrive-index#4]
`.tar`files doesnt starts downloading.showing downloading option and just getting cancelled while we try to download.

![IMG_20200711_185025_887](https://user-images.githubusercontent.com/20116017/87225141-95995f00-c3a8-11ea-991d-9523be8b2e51.jpg)
![IMG_20200711_185824_420](https://user-images.githubusercontent.com/20116017/87225143-992ce600-c3a8-11ea-9e0a-0cd66acdcaae.jpg)
![IMG_20200711_185023_475](https://user-images.githubusercontent.com/20116017/87225145-9c27d680-c3a8-11ea-8e95-b2402f1d21b3.jpg)

Proofs are attached.Kindly fix the bugs.

Thanks in advance

**Comment by patheticGeek** [comment]
Can you try checking logs and see if it has some errors logged out?

**Comment by telegrambotdev** [comment]
> Can you try checking logs and see if it has some errors logged out?

lol i am sorry.now its working fine.i was tried on vm.now i tried on my ubuntu server and works great.

can you add more themes ? like material designed themes ? those are beautiful.
you can grab it from here

**Comment by telegrambotdev** [comment]
also i noticed that i cant use your gindex scirpt on other codes
because


`https://demohosting.com/api/file/download/73094102_734789193690893_683138730954790296_n.jpg.tar?id=xxxxxx`


your gdrive generates link just like this

but almost other repos supports in this format


`https://demohosting.com/filename.tar'

or 

`https://demohosting.com/api/file/download/73094102_734789193690893_683138730954790296_n.jpg.tar`


kindly dont add that `id` section in your code..you can add id before the file name if you need..because we are providing index url to other codes just like this


`https://demohosting.com/api/file/download/73094102_734789193690893_683138730954790296_n.jpg.tar`


file name must be in the end..you can add that id thing before the file name.hope you will fix this soon.Thank you

**Comment by patheticGeek** [comment]
Which other codes are you talking about? the id is query parameter in irl so it is always at the end of url .. the page name is the filename and it should not interfere with anything. I'm working on streaming video thru this link and its working fine
