### ISSUE TITLE
Is it safe to host this on heroku? 

### ISSUE THREAD

**Issue by askfriends** [patheticGeek/gdrive-index#7]
this is nice effor, thanks for sharing.

i want to know is it safe to host our td on heroku?
our heroku account will not be banned?
what are limitations if any?

Whats difference between this script and the one we host on dev.workers?

**Comment by patheticGeek** [comment]
This is just my implementation of the web worker on heroku. I plan to do some extra features on this like autoplay for like seasons in a webseries and things like that. It is completely safe as your token or client id/secret never leaves the server
