### ISSUE TITLE
Unable to setup, Heroku gives Application error

### ISSUE THREAD

**Issue by UsamaKarim** [patheticGeek/gdrive-index#9]
Hi, 
I just deployed repo on Heroku and tried to set up it, but Heroku gives Application error.

Logs here [https://gist.github.com/UsamaKarim/bfd064ce582b18b88584ff467805fede](https://gist.github.com/UsamaKarim/bfd064ce582b18b88584ff467805fede)

**Comment by shakilofficial0** [comment]
did you set the "config vars" properly?!

**Comment by UsamaKarim** [comment]
If I understand right, you told to put values in the setup, But if the setup does not run how I put values?

BTW let me try to set config vars first. I will update to you.

**Comment by shakilofficial0** [comment]
Got Your issue. First goto in config vars and add your client id and secret. Guess the programme will work and after that go to the /setup for auth and etc

**Comment by UsamaKarim** [comment]
I did same as you told but the problem still exists

**Comment by shakilofficial0** [comment]
can you connect with me in facebook?!
if i could help you instant....

**Comment by cloudoftg** [comment]
Telegram t.me/userge12
there is still issue with me while setup : "Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command"

**Comment by UsamaKarim** [comment]
> can you connect with me in facebook?!
> if i could help you instant....

Connect me on telegram [@UsamaK](https://t.me/UsamaK)

**Comment by cloudoftg** [comment]
> can you connect with me in facebook?!
> if i could help you instant....

Thanks for cooperation. Working now

**Comment by UsamaKarim** [comment]
Setup is only for generating TOKEN value, Please add config vars (CLIENT_ID, CLIENT_SECRET) and then go to https://<nameOfYourApp>.heroku.com/setup, Generate TOKEN value here and put it in config vars, You are good to go, Thanks @shakilofficial0 for helping

EDIT: Add AUTH and PARENT_FOLDER value in config vars if still any issue.

**Comment by nirajkrnrj** [comment]
I am having the same issue ,pls help in overcoming this..
@darth_vader44
